title: The Wick Editor Alternatives Database
description: A bunch of Wick alternatives
#theme: just-the-docs

url: https://rubberocket.github.io/wickalt

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
